import arcade

UNIT = 15

SCREEN_HEIGHT = 32 * UNIT
SCREEN_WIDTH = 32 * UNIT

FOOD_HEIGHT = 1 * UNIT
FOOD_WIDTH = 1 * UNIT

SNAKE_HEIGHT = 1 * UNIT
SNAKE_WIDTH = 1 * UNIT

SNAKE_LENGTH = 3

BACKGROUND_COLOR = arcade.csscolor.CORNFLOWER_BLUE
FOOD_COLOR = arcade.csscolor.GREEN
SNAKE_COLOR = arcade.csscolor.WHITE

SCREEN_TITLE = "Snake"
